# Generated by Django 5.0.4 on 2024-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('I', 'Iniciada'), ('C', 'Cancelada'), ('A', 'Agendado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
