# Generated by Django 5.0.4 on 2024-04-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('C', 'Cancelada'), ('I', 'Iniciada'), ('A', 'Agendado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
